services:
  - type: web
    name: portfolio-chatbot-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn Scripts.app:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
